{
 "title": "Insight",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "TestVariable", "query": "Test1" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# \n![Image](https://secureservercdn.net/160.153.137.170/ixq.be3.myftpupload.com/wp-content/uploads/2020/09/ipercept_technology.png )  \n\n\n"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "options": { "content": " <br>  <br> \n<h1 > </h1>\n\n " },
   "targets": [
    {}
   ]
  },
  {
   "title": "Händelser",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <b style=\"color:Red;\" > VARNING </b> | <a style=\"color:red;\" > Detta är en exempelvarning!  </a>\n</p>\n\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <a style=\"color:LightSkyBlue;\" > Meddelande </a> | Detta är ett exempelmeddelande\n</p>\n\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <a style=\"color:SpringGreen;\" > Händelse </a> | Detta är en exempelhändelse\n</p>"
   }
  },
  {
   "title": "Testhistorik ",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"V1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_trigger\")\r\n  |> filter(fn: (r) => r[\"CID\"] == \"V1\")\r\n  |> filter(fn: (r) => r[\"MID\"] == \"MID_V1_M220906_01\")\r\n  |> filter(fn: (r) => r[\"SBID\"] == \"SB_10000000aceba07e\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trigger\")\r\n  |> filter(fn: (r) => r[\"label\"] == \"True\")"
    }
   ]
  },
  {
   "title": "Tid sedan senast genomförda test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"V1\")\r\n  |> range(start: 2020-01-01, stop: -5s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_trigger\")\r\n  |> filter(fn: (r) => r[\"CID\"] == \"V1\")\r\n  |> filter(fn: (r) => r[\"MID\"] == \"MID_V1_M220906_01\")\r\n  |> filter(fn: (r) => r[\"SBID\"] == \"SB_10000000aceba07e\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trigger\")\r\n  |> filter(fn: (r) => r[\"label\"] == \"True\")"
    }
   ]
  },
  {
   "title": "Totalt antal test genomförda",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"V1\")\r\n  |> range(start: 2020-01-01, stop: -5s)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test_trigger\")\r\n  |> filter(fn: (r) => r[\"CID\"] == \"V1\")\r\n  |> filter(fn: (r) => r[\"MID\"] == \"MID_V1_M220906_01\")\r\n  |> filter(fn: (r) => r[\"SBID\"] == \"SB_10000000aceba07e\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"trigger\")\r\n  |> filter(fn: (r) => r[\"label\"] == \"True\")"
    }
   ]
  },
  { "title": "Menu", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 } },
  {
   "title": "Kollisioner",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 6, "w": 18, "x": 5, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"IPercept\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SB_1000000053d52cd9\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amplitude\")\n  |> filter(fn: (r) => r[\"_value\"] >= 1)\n  |> aggregateWindow(every: 1d, offset: -2h, fn: sum, createEmpty: true, timeSrc: \"_stop\")"
    },
    {
     "query": "from(bucket: \"IPercept\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"SB_1000000053d52cd9\")\n  |> filter(fn: (r) => r[\"_field\"] == \"amplitude\")"
    }
   ]
  },
  {
   "title": "Mest kritiska subsystem ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IPercept\")\r\n  |> range(start: 2022-04-19, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Stages\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spindleStage\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"MID_S1_M220412\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Beskrivning av förslitningsskeden",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 20 },
   "options": {
    "content": "<b style=\"color:green;\"> Stage 0: </b> Fullständigt ny maskin <br>\n<b style=\"color:SeaGreen;\">  Stage 1: </b> Mindre defekter <br>\n<b style=\"color:LightGreen;\">  Stage 2: </b> Tydliga förslitningar i form av mindre gropar <br>\n<b style=\"color:yellow;\"> Stage 3: </b> Ökad förslitning och risk för accelererad försämring <br>\n<b style=\"color:Tomato;\"> Stage 4: </b> Tydliga skador, slutgilitiga skedet av förslitning <br>\n"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 21 },
   "options": {
    "content": "# \n![Image](https://public-ipercept.s3.eu-north-1.amazonaws.com/Dashboard_pictures/Hermle+C42.png )  \n\n\n"
   }
  }
 ]
}