{
 "title": "Machine health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "# \n![Image](https://secureservercdn.net/160.153.137.170/ixq.be3.myftpupload.com/wp-content/uploads/2020/09/ipercept_technology.png )  \n\n\n"
   }
  },
  {
   "title": "Spindel",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"IPercept\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"E1_FFT\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"MID_E1_M220406_SB_100000003cb8ded3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Händelser",
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <b style=\"color:Red;\" > VARNING </b> | <a style=\"color:red;\" > Detta är en exempelvarning!  </a>\n</p>\n\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <a style=\"color:LightSkyBlue;\" > Meddelande </a> | Detta är ett exempelmeddelande\n</p>\n\n<p> <b style=\"color:grey;\"> 2022-01-01 12:00  </b>  | <a style=\"color:SpringGreen;\" > Händelse </a> | Detta är en exempelhändelse\n</p>"
   }
  },
  {
   "title": "Subsystem 1",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"IPercept\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"E1_FFT\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"MID_E1_M220406_SB_10000000434310d9\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Menu", "type": "dashlist", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 } },
  {
   "title": "Subsystem 2",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"IPercept\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"E1_FFT\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"MID_E1_M220406_SB_10000000f061c620\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 21 },
   "options": {
    "content": "# \n![Image](https://public-ipercept.s3.eu-north-1.amazonaws.com/Dashboard_pictures/Hermle+C42.png )  \n\n\n"
   }
  }
 ]
}